/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TMC;

import TMC.Classes.Block;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author Windows 8
 */
public class TMC_Application extends javax.swing.JFrame {

    ArrayList<Block> MapBlocks = new ArrayList<Block>();
    
    
    Boolean LanguagePL = false;
    String Str_ComboB_Blocks, Str_ComboB_Tanks, Str_ComboB_Background;
    String Str_LangPL, Str_LangEng;
    
    private void setLanguage (Boolean LanguagePL)
    {
        if(LanguagePL)
        {
            Str_ComboB_Blocks = "Bloczki";
            Str_ComboB_Tanks = "Spawn Tanków";
            Str_ComboB_Background = "Tło";
            
            Str_LangPL = "Polski"; 
            Str_LangEng = "Angielski";
        }
        else
        {
            Str_ComboB_Blocks = "Blocks";
            Str_ComboB_Tanks = "Tank Spawn";
            Str_ComboB_Background = "Background";
            
            Str_LangPL = "Polish"; 
            Str_LangEng = "English";
        }                       
    }
    
    private void getInfoAboutBlocks()
    {
        for (Block Block : MapBlocks) {
            System.out.println(Block.toString());
        }
    }
    private void createDefaultBlocks()
    {
        int LocationBlockX = 5;
        int LocationBlockY = 5;
        
        for (int i = 0; i < 15; i++) {
            for (int j = 0; j < 15; j++) {
                Block tmp = new Block("Assets\\Blocks_Tex\\Default_Blocks\\MetalBlock.gif",Color.RED, false, false, false, true, LocationBlockX, LocationBlockY);
                
                GridPanelJPanel.add(tmp.Bloczek);
                tmp.Bloczek.setVisible(true);
                MapBlocks.add(tmp);
                LocationBlockX+=40;
            }  
            LocationBlockY+=40;
            LocationBlockX =5;
        }
        
        
        
    }
    
    /**
     * Creates new form TMC_Application
     */
    public TMC_Application() {
        setLanguage(LanguagePL);
        
        initComponents();
        createDefaultBlocks();
        getInfoAboutBlocks();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainJPanel = new javax.swing.JPanel();
        GridPanelJPanel = new javax.swing.JPanel();
        jPanel_Tools = new javax.swing.JPanel();
        jComboBox_CreatingMapOptions = new javax.swing.JComboBox<>();
        jPanel_Items = new javax.swing.JPanel();
        jLabel_Description = new javax.swing.JLabel();
        MenuJMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tank Map Creator");
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 700));

        MainJPanel.setBackground(new java.awt.Color(204, 204, 255));
        MainJPanel.setMaximumSize(new java.awt.Dimension(800, 636));
        MainJPanel.setMinimumSize(new java.awt.Dimension(800, 636));
        MainJPanel.setPreferredSize(new java.awt.Dimension(800, 636));
        MainJPanel.setVerifyInputWhenFocusTarget(false);

        GridPanelJPanel.setBackground(new java.awt.Color(204, 204, 204));
        GridPanelJPanel.setAlignmentX(10.0F);
        GridPanelJPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GridPanelJPanel.setMaximumSize(new java.awt.Dimension(610, 610));
        GridPanelJPanel.setMinimumSize(new java.awt.Dimension(610, 610));
        GridPanelJPanel.setPreferredSize(new java.awt.Dimension(610, 610));

        javax.swing.GroupLayout GridPanelJPanelLayout = new javax.swing.GroupLayout(GridPanelJPanel);
        GridPanelJPanel.setLayout(GridPanelJPanelLayout);
        GridPanelJPanelLayout.setHorizontalGroup(
            GridPanelJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        GridPanelJPanelLayout.setVerticalGroup(
            GridPanelJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        jPanel_Tools.setBackground(new java.awt.Color(255, 102, 102));

        jComboBox_CreatingMapOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { Str_ComboB_Blocks, Str_ComboB_Tanks, Str_ComboB_Background }));
        jComboBox_CreatingMapOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_CreatingMapOptionsActionPerformed(evt);
            }
        });

        jPanel_Items.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout jPanel_ItemsLayout = new javax.swing.GroupLayout(jPanel_Items);
        jPanel_Items.setLayout(jPanel_ItemsLayout);
        jPanel_ItemsLayout.setHorizontalGroup(
            jPanel_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_ItemsLayout.setVerticalGroup(
            jPanel_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_ToolsLayout = new javax.swing.GroupLayout(jPanel_Tools);
        jPanel_Tools.setLayout(jPanel_ToolsLayout);
        jPanel_ToolsLayout.setHorizontalGroup(
            jPanel_ToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ToolsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel_ToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Items, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_ToolsLayout.createSequentialGroup()
                        .addComponent(jComboBox_CreatingMapOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_ToolsLayout.setVerticalGroup(
            jPanel_ToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ToolsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox_CreatingMapOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Items, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Description.setBackground(new java.awt.Color(153, 255, 255));
        jLabel_Description.setText("Opis...");
        jLabel_Description.setMaximumSize(new java.awt.Dimension(30, 15));
        jLabel_Description.setMinimumSize(new java.awt.Dimension(30, 15));

        javax.swing.GroupLayout MainJPanelLayout = new javax.swing.GroupLayout(MainJPanel);
        MainJPanel.setLayout(MainJPanelLayout);
        MainJPanelLayout.setHorizontalGroup(
            MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainJPanelLayout.createSequentialGroup()
                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GridPanelJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Tools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        MainJPanelLayout.setVerticalGroup(
            MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Tools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainJPanelLayout.createSequentialGroup()
                .addComponent(GridPanelJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Description, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Plik");

        jMenuItem1.setText("Nowy");
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Zapisz");
        jMenu1.add(jMenuItem3);

        MenuJMenu.add(jMenu1);

        jMenu2.setText("Edycja");
        MenuJMenu.add(jMenu2);

        setJMenuBar(MenuJMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_CreatingMapOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_CreatingMapOptionsActionPerformed
        switch(jComboBox_CreatingMapOptions.getSelectedIndex())
        {
            case 0:
                jPanel_Items.setBackground(Color.GREEN);
                ShowInfo("Ustawiamy bloczki");
                break;
            case 1:
                jPanel_Items.setBackground(Color.blue);
                ShowInfo("Ustawiamy Spawny Tanków");
                break;
            
            case 2:
                jPanel_Items.setBackground(Color.red);
                ShowInfo("Ustawiamy BackGround");
                break;
        }
        
    }//GEN-LAST:event_jComboBox_CreatingMapOptionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TMC_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TMC_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TMC_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TMC_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TMC_Application().setVisible(true);
                
            }
        });
    }

    
    private void ShowInfo(String Info)
    {
        jLabel_Description.setText(Info);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GridPanelJPanel;
    private javax.swing.JPanel MainJPanel;
    private javax.swing.JMenuBar MenuJMenu;
    private javax.swing.JComboBox<String> jComboBox_CreatingMapOptions;
    private javax.swing.JLabel jLabel_Description;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel_Items;
    private javax.swing.JPanel jPanel_Tools;
    // End of variables declaration//GEN-END:variables
}
